/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sh.kaden.ics4u.water;

/**
 *
 * @author kaden
 */
public class WaterQuality extends javax.swing.JFrame {
    
    int[] pollutant = new int[100];
    int totalReadings;
    int count;

    /**
     * Creates new form WaterQuality
     */
    public WaterQuality() {
        initComponents();
        this.pnlInput.setVisible(false);
        this.pnlOutput.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberOfReadings = new javax.swing.JLabel();
        readingsNumber = new javax.swing.JSpinner();
        buttonEnter = new javax.swing.JButton();
        pnlInput = new javax.swing.JPanel();
        enterReadingsLabel = new javax.swing.JLabel();
        readingInput = new javax.swing.JTextField();
        enterReadingButton = new javax.swing.JButton();
        pnlOutput = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberOfReadings.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        numberOfReadings.setText("Number of Readings");
        getContentPane().add(numberOfReadings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));
        getContentPane().add(readingsNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 20));

        buttonEnter.setText("Enter Data");
        buttonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnterActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 20));

        pnlInput.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        enterReadingsLabel.setText("Enter reading: ");

        enterReadingButton.setText("OK");
        enterReadingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterReadingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputLayout = new javax.swing.GroupLayout(pnlInput);
        pnlInput.setLayout(pnlInputLayout);
        pnlInputLayout.setHorizontalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterReadingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readingInput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterReadingButton)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        pnlInputLayout.setVerticalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterReadingsLabel)
                    .addComponent(readingInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterReadingButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(pnlInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 60));

        pnlOutput.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textOutput.setColumns(20);
        textOutput.setRows(5);
        jScrollPane1.setViewportView(textOutput);

        javax.swing.GroupLayout pnlOutputLayout = new javax.swing.GroupLayout(pnlOutput);
        pnlOutput.setLayout(pnlOutputLayout);
        pnlOutputLayout.setHorizontalGroup(
            pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOutputLayout.setVerticalGroup(
            pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, 376, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnterActionPerformed
        this.totalReadings = (int) this.readingsNumber.getValue();
        this.count = 1;
        this.enterReadingsLabel.setText("Enter reading: "+this.count);
        this.pnlInput.setVisible(true);
    }//GEN-LAST:event_buttonEnterActionPerformed

    private void enterReadingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterReadingButtonActionPerformed
        if (this.readingInput.getText().equals("")) {
            return;
        }
        
        this.pollutant[this.count] = Integer.parseInt(this.readingInput.getText());
        this.readingInput.setText("");
        this.count++;
        
        if (this.count <= this.totalReadings) {
            this.enterReadingsLabel.setText("Enter reading: "+Integer.toString(this.count));
        } else {
            this.pnlInput.setVisible(false);
            this.pnlOutput.setVisible(true);
            
            String s = "Readings: \n";
            double sum = 0;
            double mean;
            
            int min = this.pollutant[1];
            int max = this.pollutant[1];
            
            for (int i = 1; i <= totalReadings; i++) {
                final int value = this.pollutant[i];
                s += "  " + Integer.toString(value)+"\n";
                sum += value;
                
                if (value > max) {
                    max = value;
                }
                
                if (value < min) {
                    min = value;
                }
            }
            
            mean = sum / this.totalReadings;
            s += String.format("Mean, min, max: %.1f, %d, %d", mean, min, max);
            
            this.textOutput.setText(s);
        }
    }//GEN-LAST:event_enterReadingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaterQuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaterQuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaterQuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaterQuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaterQuality().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnter;
    private javax.swing.JButton enterReadingButton;
    private javax.swing.JLabel enterReadingsLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numberOfReadings;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JPanel pnlOutput;
    private javax.swing.JTextField readingInput;
    private javax.swing.JSpinner readingsNumber;
    private javax.swing.JTextArea textOutput;
    // End of variables declaration//GEN-END:variables
}
