/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sh.kaden.ics4u.grades;

import java.awt.Color;

/**
 *
 * @author kaden
 */
public class StudentGrades extends javax.swing.JFrame {

    /**
     * Creates new form StudentGrades
     */
    public StudentGrades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentLabel = new javax.swing.JLabel();
        studentNameField = new javax.swing.JTextField();
        submissionLabel = new javax.swing.JLabel();
        markField = new javax.swing.JTextField();
        markLabel = new javax.swing.JLabel();
        submissionBox = new javax.swing.JComboBox<>();
        gradeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        studentLabel.setText("Student Name: ");
        getContentPane().add(studentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        studentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(studentNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 20));

        submissionLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        submissionLabel.setText("Submission: ");
        getContentPane().add(submissionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 20));

        markField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markFieldActionPerformed(evt);
            }
        });
        getContentPane().add(markField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 90, 20));

        markLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        markLabel.setText("Mark: %");
        getContentPane().add(markLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 20));

        submissionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIrst", "Second" }));
        submissionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submissionBoxActionPerformed(evt);
            }
        });
        getContentPane().add(submissionBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 90, 20));

        gradeButton.setText("Grade");
        gradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gradeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 90, 30));

        gradeTextArea.setColumns(20);
        gradeTextArea.setLineWrap(true);
        gradeTextArea.setRows(5);
        jScrollPane1.setViewportView(gradeTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameFieldActionPerformed

    private void markFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markFieldActionPerformed

    private void submissionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submissionBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submissionBoxActionPerformed

    private void gradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeButtonActionPerformed
        // Using double instead of int for mark value because I want to
        // accurately round up to the nearest integer. Casting to (int) just
        // removes the non-integral part of the number, and doesn't execute
        // any rounding logic.
        //
        // My program also supports something like "50.5" as a mark.
        try {
            final String submission = (String) this.submissionBox.getSelectedItem();
            final String name = this.studentNameField.getText();
            double studentMark = Double.parseDouble(this.markField.getText());

            if (0 > studentMark || studentMark > 100) {
                this.showError("Mark must be between 0 and 100.");
                return;
            }
            
            if (submission.equals("Second")) {
                if (studentMark > 40) {
                    studentMark = 40;
                }
            }
            
            final long mark = Math.round(studentMark);
            final String rating = this.rate(mark);

            this.showText(name, String.format("Mark: %d%%", mark), rating);
        } catch (final Exception e) {
            this.showError("Mark must be an integer or a double.");
        }
    }//GEN-LAST:event_gradeButtonActionPerformed

    private void showError(final String error) {
        this.gradeTextArea.setText(error);
        this.gradeTextArea.setForeground(Color.RED);
    }
    
    private void showText(final String... text) {
        this.gradeTextArea.setText(String.join("\n", text));
        this.gradeTextArea.setForeground(Color.BLACK);
    }
    
    private String rate(final double mark) {
        if (mark >= 70) return "Distinction";
        if (mark >= 60) return "Merit";
        if (mark >= 40) return "Pass";
        return "Fail";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gradeButton;
    private javax.swing.JTextArea gradeTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField markField;
    private javax.swing.JLabel markLabel;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JTextField studentNameField;
    private javax.swing.JComboBox<String> submissionBox;
    private javax.swing.JLabel submissionLabel;
    // End of variables declaration//GEN-END:variables
}
