/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sh.kaden.ics4u.watertank;

/**
 *
 * @author kaden
 */
public class WaterTank extends javax.swing.JFrame {

    /**
     * Creates new form WaterTank
     */
    public WaterTank() {
        initComponents();
        this.errorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lengthLabel = new javax.swing.JLabel();
        lengthInput = new javax.swing.JTextField();
        widthInput = new javax.swing.JTextField();
        widthLabel = new javax.swing.JLabel();
        heightInput = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        volumeLabel = new javax.swing.JLabel();
        volumeOutput = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        areaOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sh/kaden/ics4u/watertank/resources/tank.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, -1));

        lengthLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lengthLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lengthLabel.setText("L =");
        getContentPane().add(lengthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, 40));
        getContentPane().add(lengthInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 260, 40));
        getContentPane().add(widthInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 260, 40));

        widthLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        widthLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        widthLabel.setText("W =");
        getContentPane().add(widthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, 40));
        getContentPane().add(heightInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 260, 40));

        heightLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        heightLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        heightLabel.setText("H =");
        getContentPane().add(heightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 40));

        volumeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        volumeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        volumeLabel.setText("Volume =");
        getContentPane().add(volumeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 100, 40));

        volumeOutput.setEditable(false);
        getContentPane().add(volumeOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 260, 40));

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calculateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 360, 180, 30));

        errorLabel.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 160, 30));

        areaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        areaLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        areaLabel.setText("Area =");
        getContentPane().add(areaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 100, 40));

        areaOutput.setEditable(false);
        getContentPane().add(areaOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 260, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        final String lengthString = this.lengthInput.getText();
        final String heightString = this.heightInput.getText();
        final String widthString = this.widthInput.getText();
        
        if (lengthString.isBlank() || heightString.isBlank() || widthString.isBlank()) {
            this.showError("Cannot use blank values.");
            return;
        }
        
        double length;
        double height;
        double width;
        
        try {
            length = Double.parseDouble(lengthString);
        } catch(final Exception e) {
            this.showError("Length is not a number.");
            return;
        }
        
        try {
            width = Double.parseDouble(widthString);
        } catch(final Exception e) {
            this.showError("Width is not a number.");
            return;
        }
                
        try {
            height = Double.parseDouble(heightString);
        } catch(final Exception e) {
            this.showError("Height is not a number.");
            return;
        }
        
        final double volume = length * width * height;
        final double area = (length * width) + 2 * (length * width) + 2 * (length * width);
        this.volumeOutput.setText(Double.toString(volume));
        this.areaOutput.setText(Double.toString(area));
        this.showError(null);
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void showError(final String error) {
        if (error == null) {
            this.errorLabel.setVisible(false);
            return;
        }
        this.errorLabel.setText(error);
        this.errorLabel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaterTank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaterTank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaterTank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaterTank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaterTank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaLabel;
    private javax.swing.JTextField areaOutput;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField heightInput;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lengthInput;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JTextField volumeOutput;
    private javax.swing.JTextField widthInput;
    private javax.swing.JLabel widthLabel;
    // End of variables declaration//GEN-END:variables
}
